package migrate

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestModuleVersionAndNestedModules(t *testing.T) {
	for _, v := range []string{"1.25", "1.25.0", "1.26.2", "1.27.1", "2.0"} {
		if !atLeast125(v) {
			t.Errorf("rejected %s", v)
		}
	}
	for _, v := range []string{"", "unknown", "1", "1.24.9", "1.25.garbage", "1.-25", "v1.25"} {
		if atLeast125(v) {
			t.Errorf("accepted %s", v)
		}
	}
	file := fixture(t, "1.25", "package example")
	dir := filepath.Dir(file)
	child := filepath.Join(dir, "nested")
	if err := os.Mkdir(child, 0700); err != nil {
		t.Fatal(err)
	}
	if got := moduleVersion(child); got != "1.25" {
		t.Fatal(got)
	}
	if err := os.WriteFile(filepath.Join(child, "go.mod"), []byte("module nested\ngo 1.23 // comment\n"), 0600); err != nil {
		t.Fatal(err)
	}
	if got := moduleVersion(child); got != "1.23" {
		t.Fatal(got)
	}
	if err := os.WriteFile(filepath.Join(child, "go.mod"), []byte("module nested\n"), 0600); err != nil {
		t.Fatal(err)
	}
	if got := moduleVersion(child); got != "unknown" {
		t.Fatal(got)
	}
	if got := moduleVersion(t.TempDir()); got != "unknown" {
		t.Fatal(got)
	}
}

func TestScanSkipsExcludedTreesAndRejectsMalformedSource(t *testing.T) {
	file := fixture(t, "1.25", `package example
import("testing";"time")
func TestClock(t *testing.T){time.Sleep(time.Second)}`)
	dir := filepath.Dir(file)
	for _, name := range []string{"vendor", "testdata", ".hidden", "node_modules"} {
		sub := filepath.Join(dir, name)
		if err := os.Mkdir(sub, 0700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(sub, "bad_test.go"), []byte("not Go"), 0600); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.WriteFile(filepath.Join(dir, "notes.txt"), []byte("not Go"), 0600); err != nil {
		t.Fatal(err)
	}
	r, err := Scan(dir)
	if err != nil || r.Files != 1 || len(r.Candidates) != 1 {
		t.Fatalf("%#v %v", r, err)
	}
	if _, err := Scan(filepath.Join(dir, "missing")); err == nil {
		t.Fatal("missing root accepted")
	}
	if _, err := Scan(filepath.Join(dir, "testdata")); err == nil {
		t.Fatal("explicit malformed root accepted")
	}
	t.Run("symlink", func(t *testing.T) {
		if err := os.Symlink(file, filepath.Join(dir, "link_test.go")); err != nil {
			t.Skip(err)
		}
		r, err := Scan(dir)
		if err != nil || r.Files != 1 {
			t.Fatalf("symlink counted: %#v %v", r, err)
		}
	})
}

func TestScanRejectsNonTestsAndDynamicSubtests(t *testing.T) {
	file := fixture(t, "1.25", `package example
import("testing";"time")
type Suite struct{}
func (Suite) TestMethod(t *testing.T){time.Sleep(time.Second)}
func Testlower(t *testing.T){time.Sleep(time.Second)}
func TestNoArg(){time.Sleep(time.Second)}
func TestUnnamed(*testing.T){time.Sleep(time.Second)}
func TestBlank(_ *testing.T){time.Sleep(time.Second)}
func TestValue(t testing.T){time.Sleep(time.Second)}
func TestWrong(t *testing.B){time.Sleep(time.Second)}
func TestResults(t *testing.T) int {time.Sleep(time.Second);return 0}
func Test(t *testing.T){}
func TestDecl(t *testing.T)
func TestParent(t *testing.T){
 name:="dynamic"
 t.Run(name,func(t *testing.T){time.Sleep(time.Second)})
 t.Run("function",helper)
 t.Run("malformed")
 t.Run("wrong",func(t *testing.B){time.Sleep(time.Second)})
 t.Run("nested",func(t *testing.T){t.Run("leaf",func(t *testing.T){time.Sleep(time.Second)})})
}
`)
	r, err := Scan(filepath.Dir(file))
	if err != nil {
		t.Fatal(err)
	}
	if len(r.Candidates) != 1 || r.Candidates[0].Test != "TestParent/nested/leaf" {
		t.Fatalf("got %#v", r.Candidates)
	}
}

func TestPatchRefusalCases(t *testing.T) {
	for _, tc := range []struct {
		name, code string
		names      []string
	}{
		{"empty_selection", "package example", nil},
		{"empty_name", "package example", []string{""}},
		{"duplicate", "package example", []string{"TestA", "TestA"}},
		{"syntax", "package", []string{"TestA"}},
		{"no_timing", `package example; import "testing"; func TestA(t *testing.T){t.Log("ok")}`, []string{"TestA"}},
		{"import_exists_elsewhere", `package example;import("testing";"time";"testing/synctest");func TestA(t *testing.T){time.Sleep(time.Second)};func TestB(t *testing.T){synctest.Wait()}`, []string{"TestA"}},
		{"generated", `// Code generated by tool. DO NOT EDIT.
package example;import("testing";"time");func TestA(t *testing.T){time.Sleep(time.Second)}`, []string{"TestA"}},
		{"dot_import", `package example;import("testing";"time";. "fmt");func TestA(t *testing.T){time.Sleep(time.Second)}`, []string{"TestA"}},
		{"deadline", `package example;import("testing";"time");func TestA(t *testing.T){t.Deadline();time.Sleep(time.Second)}`, []string{"TestA"}},
		{"parent_t_inside_bubble", `package example;import("testing";"time";"testing/synctest");func TestA(t *testing.T){synctest.Test(t,func(inner *testing.T){t.Run("child",func(t *testing.T){time.Sleep(0)})})}`, []string{"TestA/child"}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			file := fixture(t, "1.25", tc.code)
			if _, err := Patch(file, tc.names); err == nil {
				t.Fatal("unsafe or invalid selection accepted")
			}
		})
	}
	if _, err := Patch(filepath.Join(t.TempDir(), "absent_test.go"), []string{"TestA"}); err == nil {
		t.Fatal("missing file accepted")
	}
	if _, err := Patch("source.go", []string{"TestA"}); err == nil {
		t.Fatal("non-test accepted")
	}
}

func TestPatchTemporaryStorageFailure(t *testing.T) {
	file := fixture(t, "1.25", clockTest)
	missing := filepath.Join(t.TempDir(), "missing")
	for _, key := range []string{"TMPDIR", "TMP", "TEMP"} {
		t.Setenv(key, missing)
	}
	if diff, err := Patch(file, []string{"TestClock"}); err == nil || diff != "" {
		t.Fatalf("temporary storage failure ignored: %q %v", diff, err)
	}
	data, err := os.ReadFile(file)
	if err != nil || string(data) != clockTest {
		t.Fatal("source changed after diff failure")
	}
}

func TestAllTimingSignalsAndExternalBoundaries(t *testing.T) {
	file := fixture(t, "1.25", `package example
import("testing";"time";"context";"github.com/stretchr/testify/assert";"os/exec";"database/sql";"runtime")
func TestSignals(t *testing.T){
time.Sleep(1);time.After(1);time.AfterFunc(1,nil);time.NewTimer(1);time.NewTicker(1);time.Tick(1)
time.Now();time.Since(time.Now());time.Until(time.Now())
context.WithTimeout(nil,1);context.WithDeadline(nil,time.Now());context.WithTimeoutCause(nil,1,nil);context.WithDeadlineCause(nil,time.Now(),nil)
assert.Eventually(t,nil,1,1);exec.Command("false");sql.Open("","");runtime.Gosched()
}`)
	r, err := Scan(filepath.Dir(file))
	if err != nil {
		t.Fatal(err)
	}
	c := r.Candidates[0]
	if len(c.Signals) != 11 || c.Status != "manual" || len(c.Reasons) != 4 {
		t.Fatalf("got %#v", c)
	}
}

func TestPatchStatementPositionsAndGitFailure(t *testing.T) {
	file := fixture(t, "1.25", `package example
// import documentation
import("testing";"time")
func TestA(t *testing.T){
defer time.Sleep(0)
go time.Sleep(0)
for i:=0;i<1;time.Sleep(0){i++}
switch 1 { case 1: time.Sleep(0) }
select { default: time.Sleep(0) }
if true { time.Sleep(0) }
}`)
	diff, err := Patch(file, []string{"TestA"})
	if err != nil {
		t.Fatal(err)
	}
	if strings.Count(diff, "+\t\tsynctest.Wait()")+strings.Count(diff, "+\t\t\tsynctest.Wait()") != 3 {
		t.Fatalf("wrong Wait placement:\n%s", diff)
	}
	t.Setenv("PATH", t.TempDir())
	if _, err := Patch(file, []string{"TestA"}); err == nil {
		t.Fatal("missing Git accepted")
	}
}

func TestUnifiedUnchangedAndGitExitFailure(t *testing.T) {
	if diff, err := unified("x.go", "package x\n", "package x\n"); err != nil || diff != "" {
		t.Fatalf("%q %v", diff, err)
	}
	// An actual failed executable should not be treated as diff exit status 1.
	if _, err := exec.LookPath("git"); err != nil {
		t.Fatal(err)
	}
	t.Setenv("GIT_CONFIG_COUNT", "1")
	t.Setenv("GIT_CONFIG_KEY_0", "invalid-key")
	t.Setenv("GIT_CONFIG_VALUE_0", "bad")
	if _, err := unified("x.go", "before\n", "after\n"); err == nil {
		t.Fatal("Git configuration failure ignored")
	}
}
